In [3]:
danhsach1 = [1. , 3.]
danhsach2 = [5. , 7.]
danhsach = danhsach1 + danhsach2 
danhsach

[1.0, 3.0, 5.0, 7.0]

In [4]:
danhsach1 = [1. , 3.]
danhsach2 = [5. , 7.]
danhsach = danhsach1 + danhsach2 
danhsach_gapdoi = 2 * danhsach
danhsach_gapdoi

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [2]:
danhsach1 = [1. , 3.]
danhsach2 = [5. , 7.]
danhsach = danhsach1 + danhsach2 
print(danhsach*2)

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


In [1]:
danhsach1 = [1. , 3.]
danhsach2 = [5. , 7.]
danhsach = danhsach1 + danhsach2 
danhsach / 2 
danhsach

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [3]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"] 
thu_tu = [2, 3, 4, 1] 
diem_so = [10, 9, 8, 7] 
anh_xa = zip(thu_tu, mon_hoc, diem_so) 
anh_xa 


In [4]:
tap_hop = set(anh_xa)              # chuyển thành dạng tập hợp 
tap_hop 

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [7]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"] 
thu_tu = [2, 3, 4, 1] 
diem_so = [10, 9, 8, 7] 
anh_xa = zip(thu_tu, mon_hoc, diem_so) 
anh_xa 
lay_TT, lay_monhoc , lay_diem = zip(*anh_xa) 
lay_monhoc 

('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

In [8]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5, 10), range(15, 20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [9]:
list(zip(range(4), range(7, 12), reversed(range(11) ) ) ) 

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [12]:
x = 1
x + x + x + 2
from sympy import Symbol
x = Symbol('x')
f = x + x + x + 2 
f 


3*x + 2

In [13]:
a = Symbol('Noi') 
b = Symbol('Chim') 
3*b + 7*a 

3*Chim + 7*Noi

In [14]:
a = Symbol('Noi') 
b = Symbol('Chim') 
a.name 

'Noi'

In [16]:
b.name 

'Chim'

In [15]:
from sympy import Symbol 
x = Symbol('x') 
y = Symbol('y') 
s = x*y + y*x 
s 

2*x*y

In [17]:
p = (x+2)*(y+3) + (x+2)*(x-3) 
p

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [18]:
p = x*(x+2*x) 
p 


3*x**2

In [19]:
p = (x+2)*(y+3) + (x+2)*(x-3) 
p 

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [20]:
p = x*(-x+2*x-x) 
p 

0

In [21]:
p = (x+2)*(y+3) 
p.expand() 


x*y + 3*x + 2*y + 6

In [22]:
from sympy import factor 
bieuthuc = x**3 - y**3 
factor(bieuthuc)

(x - y)*(x**2 + x*y + y**2)

In [23]:
from sympy import expand 
bieuthuc = (x - y)*(x**2 + x*y + y**2) 
expand(bieuthuc)

x**3 - y**3

In [24]:
from sympy import Symbol 
x = Symbol('x') 
y = Symbol('y') 
bieuthuc = x*x - x*y + y*y 
bieuthuc 

x**2 - x*y + y**2

In [25]:
giatri = bieuthuc.subs({x:3, y:2}) 
giatri 

7

In [26]:
giatri = bieuthuc.subs({x:3, y:x}) 
giatri 

x**2 - 3*x + 9

In [27]:
giatri = bieuthuc.subs({x:y, y:3}) 
giatri 

9

In [28]:
giatri = bieuthuc.subs({y:x}).subs({x:3}) 
giatri 

9

In [29]:
from sympy import Symbol 
x = Symbol('x') 
y = Symbol('y') 
bieuthuc = x*x - x*y + y*y 
bieuthuc = x**2 - x*y + y**2 
bieuthuc_moi = bieuthuc.subs({x:1-y})  #  x được thay thế bằng (1-y) 
bieuthuc_moi 

y**2 - y*(1 - y) + (1 - y)**2

In [30]:
from sympy import simplify 
dongian = simplify(bieuthuc_moi) 
dongian 


3*y**2 - 3*y + 1

In [31]:
from sympy import Symbol 
from sympy import sin, cos 
x = Symbol('x') 
y = Symbol('y') 
bt = sin(x)*cos(y) + cos(x)*sin(y) 
bt_moi = simplify(bt) 
bt_moi 

sin(x + y)

In [1]:
import numpy as np
vec1 = np.array([1., 3., 5.])
vec1 * 2 

array([ 2.,  6., 10.])

In [2]:
vec1 * vec1

array([ 1.,  9., 25.])

In [3]:
vec1 /2

array([0.5, 1.5, 2.5])

In [4]:
vec1 + vec1

array([ 2.,  6., 10.])

In [5]:
vec2 = array([2., 4.])
vec1 + vec2 

NameError: name 'array' is not defined

In [6]:
vec3 = np.array([2., 4., 6.])
vec1 + vec3

array([ 3.,  7., 11.])

In [7]:
vec1 / vec3 

array([0.5       , 0.75      , 0.83333333])

In [8]:
vec1 * vec3

array([ 2., 12., 30.])

In [9]:
2* vec1 + 5* vec3

array([12., 26., 40.])

In [10]:
v = np.array([1., 3., 5.]) 
np.sum(v) 

9.0

In [11]:
v.shape

(3,)

In [12]:
v.transpose()

array([1., 3., 5.])

In [13]:
v1 = v[:2]
v1

array([1., 3.])

In [14]:
v[0] = 5
v 

array([5., 3., 5.])

In [15]:
v1 

array([5., 3.])

In [16]:
v1[:2] = [1., 2., 3.] 

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [17]:
v1[:2] = [1., 2]
v

array([1., 2., 5.])

In [18]:
v3 = 2 * v[:2] + v1 * 3 
v3

array([ 5., 10.])

In [19]:
v1 = [4, 6]
v3 

array([ 5., 10.])

In [29]:
v

array([1., 2., 5.])

In [28]:
v + 10.0 

array([11., 12., 15.])

In [27]:
np.sqrt(v) 

array([1.        , 1.41421356, 2.23606798])

In [26]:
np.cos(v) 

array([ 0.54030231, -0.41614684,  0.28366219])

In [23]:
np.sin(v)

array([ 0.84147098,  0.90929743, -0.95892427])

In [22]:
np.dot(v1, v3) 

80.0

In [21]:
v1.dot(v3)

AttributeError: 'list' object has no attribute 'dot'

In [20]:
v3.dot(v1)

80.0