In [4]:
from sympy import Symbol, solve
import numpy as np
M1 = np.array([ [9, 12], [23,30] ])
M1


array([[ 9, 12],
       [23, 30]])

In [5]:
u = np.array([ 2, 1])
tichM1u = M1.dot(u)
print(tichM1u) 

[30 76]


In [6]:
tichuM1 = u.dot(M1)
print(tichuM1) 

[41 54]


In [7]:
np.dot(M1, u) 

array([30, 76])

In [8]:
np.dot(u, M1)

array([41, 54])

In [11]:
mat1 = np.zeros( [5,5]) 
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
mat2 = np.ones( [5,5]) 
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
mat3 = mat1 + 2* mat2 
mat3

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [15]:
mat4 = mat3 
mat3[3][2] = 10 
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [17]:
mat5 = np.copy(mat3)
mat3[3][2] = 10 
mat5

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [18]:
mat6 = np.empty([4, 5]) 
mat6

array([[0.00000000e+000, 1.58101007e-322, 0.00000000e+000,
        0.00000000e+000,             nan],
       [4.94065646e-324, 8.14220184e-321, 4.94065646e-324,
        1.06749313e-311, 1.06749313e-311],
       [0.00000000e+000, 0.00000000e+000, 1.06745359e-311,
        8.14220184e-321, 4.94065646e-324],
       [1.06748136e-311, 8.14220184e-321, 1.06749262e-311,
        1.23516411e-322, 2.12199579e-314]])

In [19]:
mat7 = np.identity(4) 
mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
mat8 = np.rand([4,5])
mat8

AttributeError: module 'numpy' has no attribute 'rand'

In [21]:
mat8 = np.random.random([4,5])
mat8

array([[0.39553556, 0.3526567 , 0.70082378, 0.39439182, 0.229033  ],
       [0.20728256, 0.21873389, 0.80134026, 0.74934801, 0.17976816],
       [0.28638331, 0.82891263, 0.25561406, 0.24602625, 0.64920128],
       [0.575818  , 0.80379918, 0.83509248, 0.67664656, 0.53012282]])