In [1]:
import numpy as np 
n = 4 
X = np.array(range(1,n+1)) 
sigma = np.array([4,3,2,1]) 
def sgn_by_def(sigma): 
    ket_qua = 1.0 
    for i in range (len (X)-1): 
        for j in range(i+1,len(X)): 
            ket_qua = ket_qua * ((X[i]-X[j])/(sigma[i]-sigma[j])) 
    return int (ket_qua) 

sigma = np.array([2,1,3,4]) 
sgn_by_def(sigma)

-1

In [2]:
sigma = np.array([1,2,3,4]) 
sgn_by_def(sigma) 

1

In [3]:
sigma = np.array([4,3,2,1]) 
sgn_by_def(sigma) 

1

In [4]:
from itertools import permutations 
n = 3 
X = [] 
for i in range (1, n+1): 
    X.append(i) 
Sn = list(permutations(X))    #  tạo hoán vị của tập X 
print (Sn) 

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [5]:
def phatsinh_dinhthuc (n): 
    X = [] 
    for i in range (1, n+1): 
            X.append(i) 
    Sn = list (permutations (X)) 
    dinhthuc = " " 
    for sn in Sn: 
            sigma = np.array([1]) 
            sigma.resize([n]) 
            product = ""
            for i in range(1,n+1): 
                    sigma [sn.index(i)] = i 
                    product = product + "a"+str(i)+str(sn.index(i)+1) 
            dau = sgn_by_def (sigma) 
            if (dau != 1): 
                    product = " _ " + product 
            else: 
                    product = " + " + product 
            dinhthuc = dinhthuc + product 
    return dinhthuc

In [6]:
phatsinh_dinhthuc(2)


IndexError: index 2 is out of bounds for axis 0 with size 2

In [7]:
phatsinh_dinhthuc(3) 

'  + a11a22a33 _ a11a23a32 _ a12a21a33 + a13a21a32 + a12a23a31 _ a13a22a31'

In [9]:
def tinhtoan_dinhthuc(A):
    X = []
    import math # <-- bổ sung để sử dụng sqrt
    n = int(math.sqrt(A.size)) # <-- với ma trận vuông, kích thước là căn số
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0 # ban đầu giá trị định thức là 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1 # đặt giá trị cho tích ban đầu là 1
        for i in range(1,n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)] # lưu ý chỉ số
            #print (A[i-1][sn.index(i)])
        dau = sgn_by_def(sigma)
        if (dau != 1): # không xét trường hợp dấu = 1
            product = product * (-1) # khi dấu = -1 thì nhân với -1
        dinhthuc = dinhthuc + product
    return dinhthuc

In [11]:
A = matran = np.array([ [3,5,-8], [4, 12, -1], [2,5,3] ]) 
tinhtoan_dinhthuc(A) 

85

In [12]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg # lưu ý: hàm tính định thức của ma trận là scipy.linalg.det(A)
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1) 
detA2 = linalg.det(A2)
print (detA, detA1, detA2)

-14.0 -28.0 14.000000000000004


In [13]:
if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print ("Hai nghiệm của phương trình là: ", x1, x2)

Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [ ]:
import numpy as np
import math
from itertools import permutations

def sgn_by_def(p):
    inversions = 0
    n = len(p)
    for i in range(n):
        for j in range(i + 1, n):
            if p[i] > p[j]:
                inversions += 1
    return 1 if (inversions % 2 == 0) else -1

def tinhtoan_dinhthuc(A_mat):
    X = []
    n = int(math.sqrt(A_mat.size))

    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))

    dinhthuc = 0

    for sn in Sn:
        temp_sigma_for_sgn = np.zeros(n, dtype=int)
        current_product = 1

        for i_val in range(1, n + 1):
            row_idx = i_val - 1
            col_idx = sn.index(i_val)

            current_product *= A_mat[row_idx][col_idx]
            temp_sigma_for_sgn[col_idx] = i_val

        dau = sgn_by_def(temp_sigma_for_sgn)

        if (dau != 1):
            current_product = current_product * (-1)
        
        dinhthuc = dinhthuc + current_product
        
    return dinhthuc

A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])

detA_custom = tinhtoan_dinhthuc(A)
detA1_custom = tinhtoan_dinhthuc(A1)
detA2_custom = tinhtoan_dinhthuc(A2)

print(f"det(A) = {detA_custom}")
print(f"det(A1) = {detA1_custom}")
print(f"det(A2) = {detA2_custom}")

Kết quả tính toán định thức sử dụng hàm tinhtoan_dinhthuc():
det(A) = -14
det(A1) = -28
det(A2) = 14


In [37]:
import numpy as np
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

b = np.array([1, 3, 2])

rank_A = np.linalg.matrix_rank(A)
augmented_matrix = np.column_stack((A, b))
rank_augmented = np.linalg.matrix_rank(augmented_matrix)
if rank_A == rank_augmented:
    if rank_A == A.shape[1]:
        solution = np.linalg.solve(A, b)
        print("Hệ có nghiệm duy nhất:")
        print(f"a = {solution[0]}")
        print(f"e = {solution[1]}")
        print(f"f = {solution[2]}")
    else:
        print("Hệ có vô số nghiệm")
else:
    print("Hệ vô nghiệm")

Hệ có vô số nghiệm


In [22]:
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1], [2, 2, 1]])
1/2*TG.det() 

1.50000000000000

In [26]:
import sympy as sp 
M = sp.Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]]) 
1/6*M.det() 

-12.0000000000000

In [28]:
from sympy import *  # lúc này ta sử dụng trực tiếp thư viện 
x, y, z = symbols('x y z') 
MP = Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0, 
1, 1]]) 
MP.det()


-4*x + 3*y - 5*z - 3

In [1]:
#BT chuong 4:
#cau1 a:
import numpy as np

def minor(matrix, i, j):
    """Tính định thức của ma trận con sau khi loại hàng i và cột j"""
    sub_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return np.linalg.det(sub_matrix)

def cofactor_matrix(matrix):
    """Tính ma trận hệ số kép"""
    n = matrix.shape[0]
    cofactors = np.zeros_like(matrix, dtype=float)

    for i in range(n):
        for j in range(n):
            sign = (-1) ** (i + j)
            cofactors[i, j] = sign * minor(matrix, i, j)

    return cofactors

# --- Ví dụ ---
A = np.array([[3, 0, 2],
              [2, 0, -2],
              [0, 1, 1]])

print("Ma trận gốc A:")
print(A)

cof_matrix = cofactor_matrix(A)
print("\nMa trận hệ số kép (Cofactor Matrix):")
print(cof_matrix)


Ma trận gốc A:
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

Ma trận hệ số kép (Cofactor Matrix):
[[ 2. -2.  2.]
 [ 2.  3. -3.]
 [ 0. 10.  0.]]


In [3]:
#b
import numpy as np

def minor(matrix, i, j):
    """Tính định thức của ma trận con sau khi loại hàng i và cột j"""
    sub_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return np.linalg.det(sub_matrix)

def cofactor_matrix(matrix):
    """Tính ma trận hệ số kép"""
    n = matrix.shape[0]
    cofactors = np.zeros_like(matrix, dtype=float)

    for i in range(n):
        for j in range(n):
            sign = (-1) ** (i + j)
            cofactors[i, j] = sign * minor(matrix, i, j)

    return cofactors

def adjoint_matrix(matrix):
    """Tính ma trận liên hợp (adjoint) bằng cách chuyển vị ma trận hệ số kép"""
    cof_matrix = cofactor_matrix(matrix)
    return cof_matrix.T

# --- Ví dụ ---
A = np.array([[3, 0, 2],
              [2, 0, -2],
              [0, 1, 1]])

print("Ma trận gốc A:")
print(A)

adj_matrix = adjoint_matrix(A)
print("\nMa trận liên hợp (Adjoint Matrix):")
print(adj_matrix)


Ma trận gốc A:
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

Ma trận liên hợp (Adjoint Matrix):
[[ 2.  2.  0.]
 [-2.  3. 10.]
 [ 2. -3.  0.]]
