In [1]:
def scale(a, v):
    return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

In [ ]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)

[5, 9, 13]

In [3]:
def dotvector(v, w): 
    return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w) 

68

In [4]:
def lenvector(v):
 return dotvector(v,v)
lenvector(w) 

56

In [6]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores 

array([-1,  1,  2, -3,  5, -4])

In [7]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [8]:
scores < 0 

array([ True, False, False,  True, False,  True])

In [12]:
np.select([scores >=0, scores < 0],["so duong","so am"])

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [13]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [15]:
import numpy as np
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ])
D 

matrix([[3, 4],
        [5, 6]])

In [16]:
C = np.mat(np.random.random((5,7)))
C

matrix([[0.4592499 , 0.95909742, 0.47311882, 0.44165377, 0.90277291,
         0.34940971, 0.11688838],
        [0.21367785, 0.19619868, 0.19762481, 0.83648044, 0.9393262 ,
         0.59365415, 0.4861846 ],
        [0.56350788, 0.96109195, 0.91075669, 0.74497092, 0.11745251,
         0.13668637, 0.35600806],
        [0.48359265, 0.6891821 , 0.34920018, 0.21640732, 0.31222659,
         0.56829414, 0.68566603],
        [0.80958643, 0.94376776, 0.68954669, 0.41425161, 0.76836533,
         0.09632331, 0.06904667]])

In [17]:
A = np.mat(np.random.random((2,2)))
A 

matrix([[0.20888917, 0.90999118],
        [0.45490528, 0.1838775 ]])

In [18]:
b = np.array([(1+5j, 2j, 3j),(4, 5,
6)])
B = np.asmatrix(b)
b


array([[1.+5.j, 0.+2.j, 0.+3.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [19]:
B

matrix([[1.+5.j, 0.+2.j, 0.+3.j],
        [4.+0.j, 5.+0.j, 6.+0.j]])

In [20]:
A.T 

matrix([[0.20888917, 0.45490528],
        [0.90999118, 0.1838775 ]])

In [21]:
A.I

matrix([[-0.48962218,  2.42309072],
        [ 1.2113049 , -0.55622233]])

In [22]:
linalg.inv(A) 

array([[-0.48962218,  2.42309072],
       [ 1.2113049 , -0.55622233]])

In [23]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower) 

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [24]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper) 

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [26]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print (v_diag)


[-1 -2 -2]


In [27]:
M_diag = np.diag(v_diag) 
print (M_diag) 

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [28]:
import sympy as sp 
x = sp.Symbol('x') 
y = sp.Symbol('y') 
z = sp.Symbol('z') 
sp.solve ([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5,y-z-8],[x, y, z]) 

[(2, 7, -1)]

In [36]:
x = [1,2,3] 
y = [1,2,3] 
all([x[i]==y[i] for i in range(len(x))]) 
True 
y= [1,2,4] 
all([x[i]==y[i] for i in range(len(x))]) 
False 

False

In [35]:
import numpy as np 
np.array_equal([1, 2], [1, 2]) 
True 
np.array_equal(np.array([1,2]), np.array([1,2])) 
True 

True

In [37]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [38]:
I6 = np.identity(6)
I6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [39]:
A.size 

36

In [40]:
np.matrix.diagonal(A) 

array([ 0.,  7., 14., 21., 28., 35.])

In [41]:
A = A + I6
A

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [42]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
C 

array([ 71., 198., 325., 452., 579., 706.])

In [43]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
D 

array([[1., 2., 3., 4., 5., 6.],
       [1., 0., 1., 0., 1., 0.]])

In [46]:
E = A.dot(D)
E 

ValueError: shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)

In [51]:
E = D.dot(A)
E

array([[421., 443., 465., 487., 509., 531.],
       [ 37.,  39.,  43.,  45.,  49.,  51.]])

In [47]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
F 

array([[1., 1.],
       [2., 0.],
       [3., 1.],
       [4., 0.],
       [5., 1.],
       [6., 0.]])

In [48]:
G

array([[ 71.,   7.],
       [198.,  24.],
       [325.,  43.],
       [452.,  60.],
       [579.,  79.],
       [706.,  96.]])

In [49]:
np.linalg.inv(A) 

array([[ 0.37022901, -0.45610687, -0.28244275, -0.10877863,  0.0648855 ,
         0.23854962],
       [-0.44656489,  0.65839695, -0.23664122, -0.13167939, -0.02671756,
         0.07824427],
       [-0.26335878, -0.22709924,  0.80916031, -0.15458015, -0.11832061,
        -0.08206107],
       [-0.08015267, -0.11259542, -0.14503817,  0.82251908, -0.20992366,
        -0.24236641],
       [ 0.10305344,  0.0019084 , -0.09923664, -0.20038168,  0.69847328,
        -0.40267176],
       [ 0.28625954,  0.11641221, -0.05343511, -0.22328244, -0.39312977,
         0.4370229 ]])

In [50]:
np.linalg.inv(np.linalg.inv(A)) 

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [54]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10 
for i in range(n):
    b = A.dot(b)
print(b) 

[89 55]


In [55]:
import sympy as sp
from sympy import Symbol 
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [59]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]]) 
A


matrix([[-1,  0,  0,  1],
        [ 1, -1,  0,  0],
        [ 0,  1, -1,  0],
        [ 0,  0,  1, -1]])

In [60]:
A_nghichdao = np.linalg.inv(A)
A_nghichdao

LinAlgError: Singular matrix