In [17]:
# Câu 1: Phép toán cơ bản trên vector và ma trận (15 điểm)
# a) Tính tổng A+B và tích số 3A-2B. (5 điểm)

import numpy as np
from math import acos, degrees

# Định nghĩa các vector và ma trận
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

sum_AB = A + B
print("A + B =", sum_AB)

result_3A_2B = 3 * A - 2 * B
print("3A - 2B =", result_3A_2B)

# Câu b: Tính tích vô hướng A · B và góc giữa hai vector
dot_product = np.dot(A, B)
print("A · B =", dot_product)

do_daiA = np.linalg.norm(A)
do_daiB = np.linalg.norm(B)
print(do_daiA)
print(do_daiB)

cos_angle = dot_product / (do_daiA * do_daiB)
print("cos(θ) =", cos_angle)

angle_deg = degrees(acos(cos_angle))
print("Góc giữa A và B (độ) =", angle_deg)

A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]
A · B = -8
3.7416573867739413
6.782329983125268
cos(θ) = -0.31524416249564025
Góc giữa A và B (độ) = 108.3755542856849


In [22]:
# Câu c: Tính tích ma trận C^T * C (chuyển vị của C nhân với C)
C_transpose = C.T
print("C^T =")
print(C_transpose)

result_CTC = np.dot(C_transpose, C)
print("C^T * C =")
print(result_CTC)


C^T =
[[ 1  0  2]
 [ 2  3 -1]
 [-1  4  0]]
C^T * C =
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [28]:
# Câu2:Nhânmatrận,địnhthứcvàhạngmatrận(20điểm)
import numpy as np
# Định nghĩa các ma trận M và N
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# Câu a: Tính tích ma trận M × N (8 điểm)
# Tính tích ma trận M × N
MN = np.dot(M, N)
print("M × N =")
print(MN)

M × N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


In [31]:
# Câu b: Tính định thức của ma trận M. Nếu khả thi, giải thích lý do (6 điểm)
# Kiểm tra xem ma trận M có phải là ma trận vuông không
if M.shape[0] == M.shape[1]:
    det_M = np.linalg.det(M)
    print(f"Ma trận M là ma trận vuông")
    print(f"Định thức của M = {det_M}")
    

Ma trận M là ma trận vuông
Định thức của M = 6.66133814775094e-16


In [37]:
# Câu c: Tính hạng của ma trận N (6 điểm)
# Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print(f"Hạng của ma trận N = {rank_N}")


Hạng của ma trận N = 2


In [46]:
#Câu3:Nghịchđảomatrậnvàgiảihệphươngtrình(25điểm)
# Câu 3: Nghịch đảo ma trận và giải hệ phương trình (25 điểm)
import numpy as np
# Ma trận P
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

# Hệ phương trình: Ax = b
A = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
# Câu a: Tìm ma trận nghịch đảo của P
det_P = np.linalg.det(P)
print(f"det(P) = {det_P}")

if abs(det_P) > 1e-10:
    P_inv = np.linalg.inv(P)
    print("P^(-1) =")
    print(P_inv)
else:
    print("P không khả nghịch")

det(P) = 86.00000000000004
P^(-1) =
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]


In [43]:
# Câu b: Giải hệ phương trình bằng nghịch đảo
x = np.dot(P_inv, b)
print("Nghiệm:")
print(f"x = {x[0]}")
print(f"y = {x[1]}")
print(f"z = {x[2]}")
print(f"w = {x[3]}")

Nghiệm:
x = 0.4651162790697678
y = 2.104651162790697
z = 1.6511627906976747
w = 0.9651162790697675


In [44]:
# Câu c: Kiểm tra nghiệm
check = np.dot(P, x)
print(f"P × x = {check}")
print(f"b = {b}")
print(f"Đúng: {np.allclose(check, b)}")

P × x = [4. 7. 9. 5.]
b = [4 7 9 5]
Đúng: True


In [49]:
#Câu4:Giátrịriêng,vectorriêngvàchuẩnhóa(20điểm)
import numpy as np
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

# Câu a: Tìm các giá trị riêng của Q
print("\nCâu a: Giá trị riêng của Q")
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("Giá trị riêng:")
for i, val in enumerate(eigenvalues):
    print(f"λ{i+1} = {val}")


Câu a: Giá trị riêng của Q
Giá trị riêng:
λ1 = (3.4533976515164015+0j)
λ2 = (2.773301174241798+1.4677115087102246j)
λ3 = (2.773301174241798-1.4677115087102246j)


In [48]:
# Câu b: Tìm các vector riêng tương ứng
print("\nCâu b: Vector riêng tương ứng")
for i in range(len(eigenvalues)):
    print(f"Vector riêng ứng với λ{i+1} = {eigenvalues[i]}:")
    print(eigenvectors[:, i])



Câu b: Vector riêng tương ứng
Vector riêng ứng với λ1 = (3.4533976515164015+0j):
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng ứng với λ2 = (2.773301174241798+1.4677115087102246j):
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng ứng với λ3 = (2.773301174241798-1.4677115087102246j):
[-0.26206044+0.31354813j -0.78166743-0.j         -0.21963176-0.41685708j]


In [52]:
# Câu c: Chuẩn hóa các vector riêng (độ dài bằng 1)
print("\nCâu c: Chuẩn hóa vector riêng")
for i in range(len(eigenvalues)):
    length = np.linalg.norm(eigenvectors[:, i])
    normalized = eigenvectors[:, i] / length
    print(f"Vector riêng chuẩn hóa ứng với λ{i+1}:")
    print(normalized)
    print(f"Độ dài: {np.linalg.norm(normalized)}")


Câu c: Chuẩn hóa vector riêng
Vector riêng chuẩn hóa ứng với λ1:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Độ dài: 1.0
Vector riêng chuẩn hóa ứng với λ2:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Độ dài: 1.0
Vector riêng chuẩn hóa ứng với λ3:
[-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]
Độ dài: 1.0


In [56]:
#Câu5:Ứngdụngthựctế-Hệphươngtrìnhvàphântích(20 điểm)
import numpy as np
R = np.array([[1, -2, 3],
              [2, 0, 1],
              [-1, 1, 4]])

b = np.array([10, 8, 7])
x = np.linalg.solve(R, b)
print("Nghiệm:")
print(f"x1 = {x[0]}")
print(f"x2 = {x[1]}")  
print(f"x3 = {x[2]}")

Nghiệm:
x1 = 2.782608695652174
x2 = 0.04347826086956541
x3 = 2.4347826086956523


In [61]:

# Câu b: Xác định ma trận R có khả nghịch không và tính nghịch đảo
det_R = np.linalg.det(R)
if abs(det_R) > 1e-10:
    print("Ma trận R khả nghịch")
    R_inv = np.linalg.inv(R)
    print("R^(-1) =")
    print(R_inv)
    
    # So sánh hai nghiệm
    x2 = np.dot(R_inv, b)
    print("Nghiệm bằng nghịch đảo:")
    print(f"x1 = {x2[0]}")
    print(f"x2 = {x2[1]}")
    print(f"x3 = {x2[2]}")
else:
    print("Ma trận R không khả nghịch")

Ma trận R khả nghịch
R^(-1) =
[[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm bằng nghịch đảo:
x1 = 2.782608695652174
x2 = 0.04347826086956527
x3 = 2.4347826086956523


In [63]:
# Câu c: Tính chuẩn Frobenius của ma trận R
frobenius_norm = np.linalg.norm(R, 'fro')
print(f"||R||_F = {frobenius_norm}")
manual_calc = np.sqrt(np.sum(R**2))
print(f"Tính thủ công: {manual_calc}")

||R||_F = 6.082762530298219
Tính thủ công: 6.082762530298219
