In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng
print (tich)

32


In [2]:
np.dot(a,b) 

32

In [3]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a) 

3.7416573867739413

In [4]:
a = np.array([1,2,-3])
np.linalg.norm(a,1) 

6.0

In [8]:
import math
import numpy as np 
a = np.array([1,2,-3])
print(chuan(a, 1))

6.0


In [9]:
np.linalg.norm(a,1)


6.0

In [10]:
chuan(a, 3)

3.3019272488946263

In [11]:
np.linalg.norm(a,3) 

3.3019272488946263

In [12]:
chuan(a, 1000) 

1.0206361019360273

In [13]:
np.linalg.norm(a,1000) 

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\linalg\linalg.py:2590: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

In [15]:
from scipy import linalg
linalg.norm(a) 

3.7416573867739413

In [16]:
linalg.norm(a, 100)

3.0

In [17]:
linalg.norm(a, 1000) 

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\linalg\linalg.py:2590: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

In [18]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [30]:
v = (1.0/m)*MT.dot(mi) 

In [31]:
print(v)

[1.3 0.9 0. ]


In [40]:
import numpy as np
p = 0.136
q = 0.998
A = np.array([[q, p],
              [1 - q, 1 - p]])

print("Ma trận chuyển trạng thái A:\n", A)
x0 = 0.95
y0 = 0.05
v0 = np.array([[x0],
               [y0]])

print("Vector trạng thái ban đầu v0:\n", v0)
A_power_100 = np.linalg.matrix_power(A, 100)
print("Ma trận A^100:\n", A_power_100)
v100 = np.dot(A_power_100, v0)
print("Trạng thái sau 100 tuần (x100, y100):\n", v100)
v100_rounded = np.round(v100, 4)
print("Trạng thái sau 100 tuần (làm tròn):\n", v100_rounded)

Ma trận chuyển trạng thái A:
 [[0.998 0.136]
 [0.002 0.864]]
Vector trạng thái ban đầu v0:
 [[0.95]
 [0.05]]
Ma trận A^100:
 [[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]
Trạng thái sau 100 tuần (x100, y100):
 [[0.98550723]
 [0.01449277]]
Trạng thái sau 100 tuần (làm tròn):
 [[0.9855]
 [0.0145]]


In [42]:
import numpy as np
A_system = np.array([[1, -68],
                     [1,  1]])

b_system = np.array([0, 1])
v_equilibrium = np.linalg.solve(A_system, b_system)
print("Ma trận hệ số của hệ phương trình:\n", A_system)
print("\nVector hằng số của hệ phương trình:\n", b_system)
print("\nTrạng thái cân bằng [x, y]:\n", v_equilibrium)
x_eq = v_equilibrium[0]
y_eq = v_equilibrium[1]
print(f"\nGiá trị x cân bằng (tỷ lệ có việc làm): {x_eq:.4f}")
print(f"Giá trị y cân bằng (tỷ lệ thất nghiệp): {y_eq:.4f}")

Ma trận hệ số của hệ phương trình:
 [[  1 -68]
 [  1   1]]

Vector hằng số của hệ phương trình:
 [0 1]

Trạng thái cân bằng [x, y]:
 [0.98550725 0.01449275]

Giá trị x cân bằng (tỷ lệ có việc làm): 0.9855
Giá trị y cân bằng (tỷ lệ thất nghiệp): 0.0145


In [22]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([[x],[y]])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [49]:
import numpy as np
A_he_so = np.array([[1, -68],
                    [1,  1]])

b_hang_so = np.array([0, 1])
ket_qua = np.linalg.solve(A_he_so, b_hang_so)
print("Ma trận hệ số của hệ phương trình:\n", A_he_so)
print("\nVector hằng số:\n", b_hang_so)
print("\nTrạng thái cân bằng [x, y]:\n", ket_qua)
x_can_bang = ket_qua[0]
y_can_bang = ket_qua[1]
print(f"\nGiá trị x cân bằng (tỷ lệ có việc làm): {x_can_bang:.6f}")
print(f"Giá trị y cân bằng (tỷ lệ thất nghiệp): {y_can_bang:.6f}")

Ma trận hệ số của hệ phương trình:
 [[  1 -68]
 [  1   1]]

Vector hằng số:
 [0 1]

Trạng thái cân bằng [x, y]:
 [0.98550725 0.01449275]

Giá trị x cân bằng (tỷ lệ có việc làm): 0.985507
Giá trị y cân bằng (tỷ lệ thất nghiệp): 0.014493


In [23]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [24]:
print (sympy.pretty(nghiem)) 

[-7, 3]


In [50]:
import numpy as np
A = np.array([[1, 6],
              [5, 2]])

u = np.array([[6],
              [-5]])

Au = np.dot(A, u)
negative_4u = -4 * u
print("Ma trận A:\n", A)
print("\nVector u:\n", u)
print("\nTích Au:\n", Au)
print("\nTích -4u:\n", negative_4u)
if np.array_equal(Au, negative_4u):
    print("\nAu = -4u đã được chứng minh.")
else:
    print("\nAu != -4u. Có lỗi trong tính toán hoặc dữ liệu.")

Ma trận A:
 [[1 6]
 [5 2]]

Vector u:
 [[ 6]
 [-5]]

Tích Au:
 [[-24]
 [ 20]]

Tích -4u:
 [[-24]
 [ 20]]

Au = -4u đã được chứng minh.


In [25]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) 
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [26]:
A.dot(P) 

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [27]:
P.dot(D) 

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [28]:
P @ (D ** 1000) @ P1 

array([[-6.25396533e+08, -3.52488701e+08],
       [-3.52488701e+08,  3.14573335e+08]])

In [29]:
print (D **2)

[[49  0]
 [ 0  9]]


In [52]:
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
print(f"Vector u: {u}")
print(f"Vector v: {v}\n")
# a. Khoảng cách giữa 2 vector u và v: ||u - v||
diff_uv = u - v
distance_uv = np.linalg.norm(diff_uv)
print(f"a. Khoảng cách giữa u và v (||u - v||): {distance_uv:.4f}")
# b. Góc theta của 2 vector u và v
dot_product_uv = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
if norm_u == 0 or norm_v == 0:
    print("b. Không thể tính góc nếu một trong các vector là vector 0.")
else:
    cos_theta = dot_product_uv / (norm_u * norm_v)
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    theta_radians = np.arccos(cos_theta)
    theta_degrees = np.degrees(theta_radians)
    print(f"b. Tích vô hướng <u, v>: {dot_product_uv:.4f}")
    print(f"   Chuẩn của u (||u||): {norm_u:.4f}")
    print(f"   Chuẩn của v (||v||): {norm_v:.4f}")
    print(f"   Cos(theta): {cos_theta:.4f}")
    print(f"   Góc theta (radian): {theta_radians:.4f}")
    print(f"   Góc theta (độ): {theta_degrees:.4f}")

# c. Phép chiếu trực giao p của u lên v
dot_product_vv = np.dot(v, v)

if dot_product_vv == 0:
    print("\nc. Không thể tính phép chiếu nếu vector v là vector 0.")
else:
    scalar_factor = dot_product_uv / dot_product_vv
    projection_p = scalar_factor * v
    print(f"\nc. Tích vô hướng <u, v>: {dot_product_uv:.4f}")
    print(f"   Tích vô hướng <v, v>: {dot_product_vv:.4f}")
    print(f"   Hệ số tỉ lệ: {scalar_factor:.4f}")
    print(f"   Phép chiếu trực giao p của u lên v: {projection_p}")

Vector u: [1 2]
Vector v: [3 4]

a. Khoảng cách giữa u và v (||u - v||): 2.8284
b. Tích vô hướng <u, v>: 11.0000
   Chuẩn của u (||u||): 2.2361
   Chuẩn của v (||v||): 5.0000
   Cos(theta): 0.9839
   Góc theta (radian): 0.1799
   Góc theta (độ): 10.3048

c. Tích vô hướng <u, v>: 11.0000
   Tích vô hướng <v, v>: 25.0000
   Hệ số tỉ lệ: 0.4400
   Phép chiếu trực giao p của u lên v: [1.32 1.76]
